/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JTable;

/**
 *
 * @author Pamella
 */
public class ViewCliente extends javax.swing.JFrame {

    /**
     * Creates new form ViewClientes
     */
    public ViewCliente() {
        initComponents();
        
        this.getContentPane().setBackground(Color.white);
        
        ImageIcon check = new ImageIcon("Images/success-menor.png");
        BtnNovoEndereco.setIcon(check);
        ImageIcon proximo = new ImageIcon("Images/next-azul-menor.png");
        BtnProximo.setIcon(proximo);
        ImageIcon anterior = new ImageIcon("Images/previous-azul-menor.png");
        BtnAnterior.setIcon(anterior);
        ImageIcon novoEndereco = new ImageIcon("Images/plus-menor.png");
        BtnMaisUmEndereco.setIcon(novoEndereco);
        ImageIcon editarEndereco = new ImageIcon("Images/edit.png");
        BtnEditarEndereco.setIcon(editarEndereco);
        ImageIcon excluirEndereco = new ImageIcon("Images/delete.png");
        BtnExcluirEndereco.setIcon(excluirEndereco);
        
        
     //   jLabel13.setText("<html><body><iframe width=\"250\" height=\"250\" frameborder=\"0\" style=\"border:0\" src=\"https://www.google.com/maps/embed/v1/search?key=AIzaSyCPgMAQV3mUYuO8rtaZILiyexwTIfpg9qA&q=record+stores+in+Seattle\"></body></html>");
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbledPanelCliente = new javax.swing.JTabbedPane();
        PanelBusca = new javax.swing.JPanel();
        jTextField9 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableCliente = new javax.swing.JTable();
        BtnVisualizar = new javax.swing.JButton();
        BtnLimparBusca = new javax.swing.JButton();
        BtnExcluir = new javax.swing.JButton();
        BtnVoltarBusca = new javax.swing.JButton();
        PanelCadastro = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        BtnSalvar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BtnLimpar = new javax.swing.JButton();
        BtnVoltarCadastro = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TxtDescricao = new javax.swing.JTextField();
        TxtRua = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TxtBairro = new javax.swing.JTextField();
        TxtNome = new javax.swing.JTextField();
        TxtComplemento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtNumero = new javax.swing.JTextField();
        TxtTelefone = new javax.swing.JTextField();
        TxtEntrega = new javax.swing.JTextField();
        BtnProximo = new javax.swing.JButton();
        BtnNovoEndereco = new javax.swing.JButton();
        BtnAnterior = new javax.swing.JButton();
        TxtId = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        LabelIdEndereco = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        BtnMaisUmEndereco = new javax.swing.JButton();
        BtnEditarEndereco = new javax.swing.JButton();
        BtnExcluirEndereco = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxTipoLogradouro = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        TxtEntrega1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        TxtEntrega2 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabbledPanelCliente.setBackground(new java.awt.Color(255, 255, 255));

        PanelBusca.setBackground(new java.awt.Color(255, 255, 255));

        jTextField9.setText("Digite sua pesquisa aqui...");

        TableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableCliente);

        BtnVisualizar.setBackground(new java.awt.Color(255, 204, 255));
        BtnVisualizar.setText("Visualizar");
        BtnVisualizar.setEnabled(false);

        BtnLimparBusca.setBackground(new java.awt.Color(102, 102, 255));
        BtnLimparBusca.setText("Limpar");

        BtnExcluir.setText("Excluir");

        BtnVoltarBusca.setText("Voltar ao Menu");

        javax.swing.GroupLayout PanelBuscaLayout = new javax.swing.GroupLayout(PanelBusca);
        PanelBusca.setLayout(PanelBuscaLayout);
        PanelBuscaLayout.setHorizontalGroup(
            PanelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBuscaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(PanelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBuscaLayout.createSequentialGroup()
                        .addComponent(BtnVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(BtnLimparBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(BtnVoltarBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE)
                    .addComponent(jTextField9))
                .addGap(22, 22, 22))
        );
        PanelBuscaLayout.setVerticalGroup(
            PanelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBuscaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addGroup(PanelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnVisualizar)
                    .addComponent(BtnLimparBusca)
                    .addComponent(BtnExcluir)
                    .addComponent(BtnVoltarBusca))
                .addGap(25, 25, 25))
        );

        TabbledPanelCliente.addTab("Busca", PanelBusca);

        PanelCadastro.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setText("Página");

        jSeparator2.setToolTipText("");
        jSeparator2.setName(""); // NOI18N

        BtnSalvar.setText("Salvar");

        jSeparator1.setToolTipText("");
        jSeparator1.setName(""); // NOI18N

        jLabel3.setText("Endereço");

        jLabel4.setText("Descrição");

        BtnLimpar.setText("Limpar");

        BtnVoltarCadastro.setText("Voltar");

        jLabel5.setText("Logradouro");

        jLabel6.setText("Bairro");

        jLabel7.setText("Número");

        jLabel8.setText("Tempo");

        jLabel9.setText("Complemento");

        jLabel1.setText("Nome");

        TxtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBairroActionPerformed(evt);
            }
        });

        jLabel2.setText("Telefone");

        TxtEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEntregaActionPerformed(evt);
            }
        });

        TxtId.setEnabled(false);

        jLabel11.setText("ID");

        LabelIdEndereco.setText("1");

        jLabel12.setText("E-mail");

        BtnMaisUmEndereco.setEnabled(false);

        BtnEditarEndereco.setEnabled(false);

        BtnExcluirEndereco.setEnabled(false);

        jLabel13.setText("jLabel13");

        jComboBoxTipoLogradouro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Avenida", "Rua" }));

        jLabel14.setText("Custo");

        TxtEntrega1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEntrega1ActionPerformed(evt);
            }
        });

        jLabel15.setText("Km");

        TxtEntrega2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEntrega2ActionPerformed(evt);
            }
        });

        jLabel16.setText("Informações da entrega");

        javax.swing.GroupLayout PanelCadastroLayout = new javax.swing.GroupLayout(PanelCadastro);
        PanelCadastro.setLayout(PanelCadastroLayout);
        PanelCadastroLayout.setHorizontalGroup(
            PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(PanelCadastroLayout.createSequentialGroup()
                .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelCadastroLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(TxtId, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(TxtNome))
                    .addGroup(PanelCadastroLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(TxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCadastroLayout.createSequentialGroup()
                .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelCadastroLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(PanelCadastroLayout.createSequentialGroup()
                                .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PanelCadastroLayout.createSequentialGroup()
                                        .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(PanelCadastroLayout.createSequentialGroup()
                                                .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jComboBoxTipoLogradouro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(TxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(29, 36, Short.MAX_VALUE)
                                                .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(TxtRua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCadastroLayout.createSequentialGroup()
                                                        .addComponent(jLabel6)
                                                        .addGap(12, 12, 12)
                                                        .addComponent(TxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addComponent(TxtComplemento)
                                            .addComponent(TxtDescricao)))
                                    .addGroup(PanelCadastroLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(TxtEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)
                                        .addComponent(jLabel15)
                                        .addGap(18, 18, 18)
                                        .addComponent(TxtEntrega2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)
                                        .addComponent(jLabel14)
                                        .addGap(18, 18, 18)
                                        .addComponent(TxtEntrega1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelCadastroLayout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(10, 10, 10)
                                        .addComponent(jSeparator4)))
                                .addGap(33, 33, 33)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelCadastroLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(BtnNovoEndereco)
                        .addGap(31, 31, 31)
                        .addComponent(BtnMaisUmEndereco)
                        .addGap(33, 33, 33)
                        .addComponent(BtnEditarEndereco)
                        .addGap(34, 34, 34)
                        .addComponent(BtnExcluirEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelIdEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnProximo)))
                .addGap(30, 30, 30))
            .addComponent(jSeparator2)
            .addGroup(PanelCadastroLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(BtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149)
                .addComponent(BtnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129)
                .addComponent(BtnVoltarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelCadastroLayout.setVerticalGroup(
            PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadastroLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelCadastroLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel1))))
                .addGap(27, 27, 27)
                .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelCadastroLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel12))))
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCadastroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(25, 25, 25)
                        .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBoxTipoLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addComponent(TxtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addGroup(PanelCadastroLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel6))
                            .addComponent(TxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(32, 32, 32)
                        .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(TxtEntrega1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(TxtEntrega2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCadastroLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCadastroLayout.createSequentialGroup()
                        .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LabelIdEndereco)
                                .addComponent(jLabel10))
                            .addComponent(BtnProximo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnEditarEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnExcluirEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelCadastroLayout.createSequentialGroup()
                        .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnMaisUmEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnNovoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnSalvar)
                    .addComponent(BtnLimpar)
                    .addComponent(BtnVoltarCadastro))
                .addGap(23, 23, 23))
        );

        TabbledPanelCliente.addTab("Cadastro", PanelCadastro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TabbledPanelCliente)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbledPanelCliente)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBairroActionPerformed

    private void TxtEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEntregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEntregaActionPerformed

    private void TxtEntrega1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEntrega1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEntrega1ActionPerformed

    private void TxtEntrega2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEntrega2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEntrega2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                    new ViewCliente().setVisible(true);
                
            }
        });
    }

    public JTable getTableCliente() {
        return TableCliente;
    }

    public void setTableCliente(JTable TableCliente) {
        this.TableCliente = TableCliente;
    }

    public String getBairro() {
        return TxtBairro.getText();
    }

    public void setBairro(String bairro) {
        TxtBairro.setText(bairro);
    }

    public String getComplemento() {
        return TxtComplemento.getText();
    }

    public void setComplemento(String complemento) {
        TxtComplemento.setText(complemento);
    }

    public String getDescricao() {
        return TxtDescricao.getText();
    }

    public void setDescricao(String descricao) {
        TxtDescricao.setText(descricao);
    }

    public String getEntrega() {
        return TxtEntrega.getText();
    }

    public void setEntrega(String entrega) {
        TxtEntrega.setText(entrega);
    }

    public String getNome() {
        return TxtNome.getText();
    }

    public void setNome(String nome) {
        TxtNome.setText(nome);
    }

    public String getNumero() {
        return TxtNumero.getText();
    }

    public void setNumero(String numero) {
        TxtNumero.setText(numero);
    }

    public String getRua() {
        return TxtRua.getText();
    }

    public void setRua(String rua) {
        TxtRua.setText(rua);
    }

    public String getTelefone() {
        return TxtTelefone.getText();
    }

    public void setTelefone(String telefone) {
        TxtTelefone.setText(telefone);
    }
    
    public String getIdCliente() {
        return TxtId.getText();
    }

    public void setIdCliente(int idCliente) {
        TxtId.setText(String.valueOf(idCliente));
    }
    
    public String getIdEndereco() {
        return LabelIdEndereco.getText();
    }

    public void setIdEndereco(int idEndereco) {
        LabelIdEndereco.setText(String.valueOf(idEndereco));
    }
    
    public String getLabelMapa() {
        return jLabel13.getText();
    }

    public void setLabelMapa(String mapa) {
        jLabel13.setText(String.valueOf(mapa));
    }
    
    public void setLabelMapa(Icon mapa) {
        jLabel13.setIcon(mapa);
    }
        
    public void addClienteListener(ActionListener listenerForjButtonCadastrar){
        BtnSalvar.addActionListener(listenerForjButtonCadastrar);
    }
    
    public void limparCamposClienteListener(ActionListener listenerForjButtonLimpar){
        BtnLimpar.addActionListener(listenerForjButtonLimpar);
    }
    
    public void voltarListener(ActionListener listenerForjButtonVoltar){
        BtnVoltarCadastro.addActionListener(listenerForjButtonVoltar);
    }
    
    public void visualizarClienteListener(ActionListener listenerForjButtonVisualizar){
        BtnVisualizar.addActionListener(listenerForjButtonVisualizar);
    }
    
    public void limparBuscaClienteListener(ActionListener listenerForjButtonLimpar){
        BtnLimparBusca.addActionListener(listenerForjButtonLimpar);
    }
    
    public void excluirClienteListener(ActionListener listenerForjButtonExcluir){
        BtnExcluir.addActionListener(listenerForjButtonExcluir);
    }
    
    public void voltarDaBuscaListener(ActionListener listenerForjButtonVoltar){
        BtnVoltarBusca.addActionListener(listenerForjButtonVoltar);
    }
    
    public void novoEnderecoListener(ActionListener listenerForjButtonNovoEndereco){
        BtnNovoEndereco.addActionListener(listenerForjButtonNovoEndereco);
    }
    
    public void proximoEndereco(ActionListener listenerForjButtonProximoEndereco){
        BtnProximo.addActionListener(listenerForjButtonProximoEndereco);
    }
    
    public void enderecoAnterior(ActionListener listenerForjButtonEnderecoAnterior){
        BtnAnterior.addActionListener(listenerForjButtonEnderecoAnterior);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAnterior;
    private javax.swing.JButton BtnEditarEndereco;
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnExcluirEndereco;
    private javax.swing.JButton BtnLimpar;
    private javax.swing.JButton BtnLimparBusca;
    private javax.swing.JButton BtnMaisUmEndereco;
    private javax.swing.JButton BtnNovoEndereco;
    private javax.swing.JButton BtnProximo;
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JButton BtnVisualizar;
    private javax.swing.JButton BtnVoltarBusca;
    private javax.swing.JButton BtnVoltarCadastro;
    private javax.swing.JLabel LabelIdEndereco;
    private javax.swing.JPanel PanelBusca;
    private javax.swing.JPanel PanelCadastro;
    private javax.swing.JTabbedPane TabbledPanelCliente;
    private javax.swing.JTable TableCliente;
    private javax.swing.JTextField TxtBairro;
    private javax.swing.JTextField TxtComplemento;
    private javax.swing.JTextField TxtDescricao;
    private javax.swing.JTextField TxtEntrega;
    private javax.swing.JTextField TxtEntrega1;
    private javax.swing.JTextField TxtEntrega2;
    private javax.swing.JTextField TxtId;
    private javax.swing.JTextField TxtNome;
    private javax.swing.JTextField TxtNumero;
    private javax.swing.JTextField TxtRua;
    private javax.swing.JTextField TxtTelefone;
    private javax.swing.JComboBox<String> jComboBoxTipoLogradouro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextFieldEmail;
    // End of variables declaration//GEN-END:variables
}
