/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JTable;

/**
 *
 * @author Pamella
 */
public class ViewCliente extends javax.swing.JFrame {

    /**
     * Creates new form ViewClientes
     */
    public ViewCliente() {
        initComponents();
        
        this.getContentPane().setBackground(Color.white);
        
        ImageIcon check = new ImageIcon("Images/success-menor.png");
        BtnNovoEndereco.setIcon(check);
        ImageIcon proximo = new ImageIcon("Images/next-azul-menor.png");
        BtnProximo.setIcon(proximo);
        ImageIcon anterior = new ImageIcon("Images/previous-azul-menor.png");
        BtnAnterior.setIcon(anterior);
        ImageIcon novoEndereco = new ImageIcon("Images/plus-menor.png");
        BtnMaisUmEndereco.setIcon(novoEndereco);
        ImageIcon editarEndereco = new ImageIcon("Images/edit.png");
        BtnEditarEndereco.setIcon(editarEndereco);
        ImageIcon excluirEndereco = new ImageIcon("Images/delete.png");
        BtnExcluirEndereco.setIcon(excluirEndereco);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbledPanelCliente = new javax.swing.JTabbedPane();
        PanelBusca = new javax.swing.JPanel();
        jTextField9 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableCliente = new javax.swing.JTable();
        BtnVisualizar = new javax.swing.JButton();
        BtnLimparBusca = new javax.swing.JButton();
        BtnExcluir = new javax.swing.JButton();
        BtnVoltarBusca = new javax.swing.JButton();
        PanelCadastro = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        BtnSalvar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BtnLimpar = new javax.swing.JButton();
        BtnVoltarCadastro = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TxtDescricao = new javax.swing.JTextField();
        TxtRua = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TxtBairro = new javax.swing.JTextField();
        TxtNome = new javax.swing.JTextField();
        TxtComplemento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtNumero = new javax.swing.JTextField();
        TxtTelefone = new javax.swing.JTextField();
        TxtEntrega = new javax.swing.JTextField();
        BtnProximo = new javax.swing.JButton();
        BtnNovoEndereco = new javax.swing.JButton();
        BtnAnterior = new javax.swing.JButton();
        TxtId = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        LabelIdEndereco = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        BtnMaisUmEndereco = new javax.swing.JButton();
        BtnEditarEndereco = new javax.swing.JButton();
        BtnExcluirEndereco = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabbledPanelCliente.setBackground(new java.awt.Color(255, 255, 255));

        PanelBusca.setBackground(new java.awt.Color(255, 255, 255));

        jTextField9.setText("Digite sua pesquisa aqui...");

        TableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableCliente);

        BtnVisualizar.setBackground(new java.awt.Color(255, 204, 255));
        BtnVisualizar.setText("Visualizar");
        BtnVisualizar.setEnabled(false);

        BtnLimparBusca.setBackground(new java.awt.Color(102, 102, 255));
        BtnLimparBusca.setText("Limpar");

        BtnExcluir.setText("Excluir");

        BtnVoltarBusca.setText("Voltar ao Menu");

        javax.swing.GroupLayout PanelBuscaLayout = new javax.swing.GroupLayout(PanelBusca);
        PanelBusca.setLayout(PanelBuscaLayout);
        PanelBuscaLayout.setHorizontalGroup(
            PanelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBuscaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(PanelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBuscaLayout.createSequentialGroup()
                        .addComponent(BtnVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(BtnLimparBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(BtnVoltarBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
                    .addComponent(jTextField9))
                .addGap(22, 22, 22))
        );
        PanelBuscaLayout.setVerticalGroup(
            PanelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBuscaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(PanelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnVisualizar)
                    .addComponent(BtnLimparBusca)
                    .addComponent(BtnExcluir)
                    .addComponent(BtnVoltarBusca))
                .addGap(25, 25, 25))
        );

        TabbledPanelCliente.addTab("Busca", PanelBusca);

        PanelCadastro.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setText("Página");

        jSeparator2.setToolTipText("");
        jSeparator2.setName(""); // NOI18N

        BtnSalvar.setText("Salvar");

        jSeparator1.setToolTipText("");
        jSeparator1.setName(""); // NOI18N

        jLabel3.setText("Endereço");

        jLabel4.setText("Descrição");

        BtnLimpar.setText("Limpar");

        BtnVoltarCadastro.setText("Voltar");

        jLabel5.setText("Rua");

        jLabel6.setText("Bairro");

        jLabel7.setText("Número");

        jLabel8.setText("Tempo de entrega");

        jLabel9.setText("Complemento");

        jLabel1.setText("Nome");

        TxtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBairroActionPerformed(evt);
            }
        });

        jLabel2.setText("Telefone");

        TxtEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEntregaActionPerformed(evt);
            }
        });

        TxtId.setEnabled(false);

        jLabel11.setText("ID");

        LabelIdEndereco.setText("1");

        jLabel12.setText("E-mail");

        BtnMaisUmEndereco.setEnabled(false);

        BtnEditarEndereco.setEnabled(false);

        BtnExcluirEndereco.setEnabled(false);

        javax.swing.GroupLayout PanelCadastroLayout = new javax.swing.GroupLayout(PanelCadastro);
        PanelCadastro.setLayout(PanelCadastroLayout);
        PanelCadastroLayout.setHorizontalGroup(
            PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addGroup(PanelCadastroLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCadastroLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(TxtId, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelCadastroLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(TxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(74, 74, 74)
                .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldEmail)
                    .addComponent(TxtNome))
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCadastroLayout.createSequentialGroup()
                .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelCadastroLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(TxtComplemento))
                    .addGroup(PanelCadastroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelCadastroLayout.createSequentialGroup()
                                .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtRua, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                                    .addComponent(TxtBairro))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                                .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PanelCadastroLayout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelCadastroLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(TxtEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(TxtDescricao)))
                    .addGroup(PanelCadastroLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(BtnNovoEndereco)
                        .addGap(30, 30, 30)
                        .addComponent(BtnMaisUmEndereco)
                        .addGap(30, 30, 30)
                        .addComponent(BtnEditarEndereco)
                        .addGap(30, 30, 30)
                        .addComponent(BtnExcluirEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addGap(3, 3, 3)
                        .addComponent(LabelIdEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnProximo)))
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCadastroLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(BtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154)
                .addComponent(BtnVoltarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(PanelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelCadastroLayout.setVerticalGroup(
            PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadastroLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(TxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(TxtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(TxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TxtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(LabelIdEndereco)
                    .addComponent(BtnNovoEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnProximo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnMaisUmEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnEditarEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnExcluirEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149)
                .addGroup(PanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnVoltarCadastro)
                    .addComponent(BtnLimpar)
                    .addComponent(BtnSalvar))
                .addGap(22, 22, 22))
        );

        BtnProximo.getAccessibleContext().setAccessibleName("");
        BtnAnterior.getAccessibleContext().setAccessibleName("");

        TabbledPanelCliente.addTab("Cadastro", PanelCadastro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbledPanelCliente)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbledPanelCliente)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEntregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEntregaActionPerformed

    private void TxtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBairroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCliente().setVisible(true);
            }
        });
    }

    public JTable getTableCliente() {
        return TableCliente;
    }

    public void setTableCliente(JTable TableCliente) {
        this.TableCliente = TableCliente;
    }

    public String getBairro() {
        return TxtBairro.getText();
    }

    public void setBairro(String bairro) {
        TxtBairro.setText(bairro);
    }

    public String getComplemento() {
        return TxtComplemento.getText();
    }

    public void setComplemento(String complemento) {
        TxtComplemento.setText(complemento);
    }

    public String getDescricao() {
        return TxtDescricao.getText();
    }

    public void setDescricao(String descricao) {
        TxtDescricao.setText(descricao);
    }

    public String getEntrega() {
        return TxtEntrega.getText();
    }

    public void setEntrega(String entrega) {
        TxtEntrega.setText(entrega);
    }

    public String getNome() {
        return TxtNome.getText();
    }

    public void setNome(String nome) {
        TxtNome.setText(nome);
    }

    public String getNumero() {
        return TxtNumero.getText();
    }

    public void setNumero(String numero) {
        TxtNumero.setText(numero);
    }

    public String getRua() {
        return TxtRua.getText();
    }

    public void setRua(String rua) {
        TxtRua.setText(rua);
    }

    public String getTelefone() {
        return TxtTelefone.getText();
    }

    public void setTelefone(String telefone) {
        TxtTelefone.setText(telefone);
    }
    
    public String getIdCliente() {
        return TxtId.getText();
    }

    public void setIdCliente(int idCliente) {
        TxtId.setText(String.valueOf(idCliente));
    }
    
    public String getIdEndereco() {
        return LabelIdEndereco.getText();
    }

    public void setIdEndereco(int idEndereco) {
        LabelIdEndereco.setText(String.valueOf(idEndereco));
    }
        
    public void addClienteListener(ActionListener listenerForjButtonCadastrar){
        BtnSalvar.addActionListener(listenerForjButtonCadastrar);
    }
    
    public void limparCamposClienteListener(ActionListener listenerForjButtonLimpar){
        BtnLimpar.addActionListener(listenerForjButtonLimpar);
    }
    
    public void voltarListener(ActionListener listenerForjButtonVoltar){
        BtnVoltarCadastro.addActionListener(listenerForjButtonVoltar);
    }
    
    public void visualizarClienteListener(ActionListener listenerForjButtonVisualizar){
        BtnVisualizar.addActionListener(listenerForjButtonVisualizar);
    }
    
    public void limparBuscaClienteListener(ActionListener listenerForjButtonLimpar){
        BtnLimparBusca.addActionListener(listenerForjButtonLimpar);
    }
    
    public void excluirClienteListener(ActionListener listenerForjButtonExcluir){
        BtnExcluir.addActionListener(listenerForjButtonExcluir);
    }
    
    public void voltarDaBuscaListener(ActionListener listenerForjButtonVoltar){
        BtnVoltarBusca.addActionListener(listenerForjButtonVoltar);
    }
    
    public void novoEnderecoListener(ActionListener listenerForjButtonNovoEndereco){
        BtnNovoEndereco.addActionListener(listenerForjButtonNovoEndereco);
    }
    
    public void proximoEndereco(ActionListener listenerForjButtonProximoEndereco){
        BtnProximo.addActionListener(listenerForjButtonProximoEndereco);
    }
    
    public void enderecoAnterior(ActionListener listenerForjButtonEnderecoAnterior){
        BtnAnterior.addActionListener(listenerForjButtonEnderecoAnterior);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAnterior;
    private javax.swing.JButton BtnEditarEndereco;
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnExcluirEndereco;
    private javax.swing.JButton BtnLimpar;
    private javax.swing.JButton BtnLimparBusca;
    private javax.swing.JButton BtnMaisUmEndereco;
    private javax.swing.JButton BtnNovoEndereco;
    private javax.swing.JButton BtnProximo;
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JButton BtnVisualizar;
    private javax.swing.JButton BtnVoltarBusca;
    private javax.swing.JButton BtnVoltarCadastro;
    private javax.swing.JLabel LabelIdEndereco;
    private javax.swing.JPanel PanelBusca;
    private javax.swing.JPanel PanelCadastro;
    private javax.swing.JTabbedPane TabbledPanelCliente;
    private javax.swing.JTable TableCliente;
    private javax.swing.JTextField TxtBairro;
    private javax.swing.JTextField TxtComplemento;
    private javax.swing.JTextField TxtDescricao;
    private javax.swing.JTextField TxtEntrega;
    private javax.swing.JTextField TxtId;
    private javax.swing.JTextField TxtNome;
    private javax.swing.JTextField TxtNumero;
    private javax.swing.JTextField TxtRua;
    private javax.swing.JTextField TxtTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextFieldEmail;
    // End of variables declaration//GEN-END:variables
}
