/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;

/**
 *
 * @author Pamella
 */
public class ViewMenu extends javax.swing.JFrame {

    /**
     * Creates new form Menuu
     */
    public ViewMenu() {
        initComponents();
        
        //colocando o form branco
        this.getContentPane().setBackground(Color.white);
        
        //imagens em labels
        ImageIcon config = new ImageIcon("Images/setting (1).png");
        jLabel2.setIcon(config);
        ImageIcon notificacao = new ImageIcon("Images/email.png");
        jLabel1.setIcon(notificacao);
        
        //imagens nos butões
        ImageIcon img = new ImageIcon("Images/document-editAA.png");
        jButtonPedidos.setIcon(img);
        ImageIcon indicadores = new ImageIcon("Images/chart (1).png");
        jButtonIndicadores.setIcon(indicadores);
        ImageIcon tarefas = new ImageIcon("Images/task-edi.png");
        jButtonTarefas.setIcon(tarefas);
        ImageIcon agenda = new ImageIcon("Images/calendar.png");
        jButtonAgenda.setIcon(agenda);
        ImageIcon receita = new ImageIcon("Images/recipe.png");
        jButtonReceitas.setIcon(receita);
        ImageIcon cliente = new ImageIcon("Images/addressbooks.png");
        jButtonClientes.setIcon(cliente);
        ImageIcon ingrediente = new ImageIcon("Images/cart.png");
        jButtonIngredientes.setIcon(ingrediente);
        ImageIcon compras = new ImageIcon("Images/shopcart.png");
        jButtonCompras.setIcon(compras);
        ImageIcon medidas = new ImageIcon("Images/balance.png");
        jButtonMedidas.setIcon(medidas);

        jButtonPedidos.setText("<html><b>Pedidos</b><br><font size='3'>Visualize e faça <br>seus pedidos</html>");
        jButtonTarefas.setText("<html><b>Tarefas</b><br><font size='3'>Cadastre, visualize<br>e edite tarefas</html>");
        jButtonAgenda.setText("<html><b>Agenda</b><br><font size='3'>Seus eventos <br>tarefas</html>");
        jButtonIndicadores.setText("<html><b>Indicadores</b><br><font size='3'>Seus eventos <br>tarefas</html>");
        jButtonReceitas.setText("<html><b>Receitas</b><br><font size='3'>Seus eventos <br>tarefas</html>");
        jButtonClientes.setText("<html><b>Clientes</b><br><font size='3'>Seus eventos <br>tarefas</html>");
        jButtonIngredientes.setText("<html><b>Ingredientes</b><br><font size='3'>Seus eventos <br>tarefas</html>");
        jButtonCompras.setText("<html><b>Compras</b><br><font size='3'>Seus eventos <br>tarefas</html>");
        jButtonMedidas.setText("<html><b>Medidas</b><br><font size='3'>Seus eventos <br>tarefas</html>");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonReceitas = new javax.swing.JButton();
        jButtonPedidos = new javax.swing.JButton();
        jButtonIngredientes = new javax.swing.JButton();
        jButtonTarefas = new javax.swing.JButton();
        jButtonClientes = new javax.swing.JButton();
        jButtonCompras = new javax.swing.JButton();
        jButtonAgenda = new javax.swing.JButton();
        jButtonIndicadores = new javax.swing.JButton();
        jButtonMedidas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DoceIra - Tela Inicial");
        setAutoRequestFocus(false);
        setBackground(Color.black);

        jButtonReceitas.setBackground(new java.awt.Color(255, 204, 255));
        jButtonReceitas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonReceitas.setText("Minhas Receitas");
        jButtonReceitas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButtonPedidos.setBackground(new java.awt.Color(255, 255, 204));
        jButtonPedidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonPedidos.setText("Pedidos");
        jButtonPedidos.setToolTipText("");
        jButtonPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButtonIngredientes.setBackground(new java.awt.Color(255, 255, 204));
        jButtonIngredientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonIngredientes.setText("Ingredientes");
        jButtonIngredientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButtonTarefas.setBackground(new java.awt.Color(204, 255, 255));
        jButtonTarefas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonTarefas.setText("Tarefas");
        jButtonTarefas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButtonClientes.setBackground(new java.awt.Color(204, 204, 255));
        jButtonClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonClientes.setText("Clientes");
        jButtonClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButtonCompras.setBackground(new java.awt.Color(204, 255, 255));
        jButtonCompras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonCompras.setText("Compras");
        jButtonCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButtonAgenda.setBackground(new java.awt.Color(255, 204, 255));
        jButtonAgenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonAgenda.setText("Agenda");
        jButtonAgenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendaActionPerformed(evt);
            }
        });

        jButtonIndicadores.setBackground(new java.awt.Color(255, 255, 204));
        jButtonIndicadores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonIndicadores.setText("Indicadores");
        jButtonIndicadores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButtonMedidas.setBackground(new java.awt.Color(255, 204, 255));
        jButtonMedidas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonMedidas.setText("Medidas");
        jButtonMedidas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jButtonCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jButtonMedidas, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonReceitas, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(jButtonPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonTarefas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonIndicadores, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(jButtonTarefas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonReceitas, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonIndicadores, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMedidas, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(402, 402, 402)
                        .addComponent(jLabel2)))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgendaActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved
        // TODO add your handling code here:
        ImageIcon config = new ImageIcon("Images/email-open.png");
        jLabel1.setIcon(config);
        
    }//GEN-LAST:event_jLabel1MouseMoved

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        ImageIcon config = new ImageIcon("Images/email.png");
        jLabel1.setIcon(config);
    }//GEN-LAST:event_jLabel1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMenu().setVisible(true);
            }
        });
    }

    public void pedidosListener(ActionListener listenerForjButtonPedidos) {
        jButtonPedidos.addActionListener(listenerForjButtonPedidos);
    }

    public void tarefasListener(ActionListener listenerForjButtonTarefas) {
        jButtonTarefas.addActionListener(listenerForjButtonTarefas);
    }

    public void agendaListener(ActionListener listenerForjButtonAgenda) {
        jButtonAgenda.addActionListener(listenerForjButtonAgenda);
    }

    public void receitasListener(ActionListener listenerForjButtonReceitas) {
        jButtonReceitas.addActionListener(listenerForjButtonReceitas);
    }

    public void clientesListener(ActionListener listenerForjButtonClientes) {
        jButtonClientes.addActionListener(listenerForjButtonClientes);
    }

    public void indicadoresListener(ActionListener listenerForjButtonIndicadores) {
        jButtonIndicadores.addActionListener(listenerForjButtonIndicadores);
    }

    public void ingredientesListener(ActionListener listenerForjButtonIngredientes) {
        jButtonIngredientes.addActionListener(listenerForjButtonIngredientes);
    }

    public void comprasListener(ActionListener listenerForjButtonCompras) {
        jButtonCompras.addActionListener(listenerForjButtonCompras);
    }

    public void medidasListener(ActionListener listenerForjButtonMedidas) {
        jButtonMedidas.addActionListener(listenerForjButtonMedidas);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgenda;
    private javax.swing.JButton jButtonClientes;
    private javax.swing.JButton jButtonCompras;
    private javax.swing.JButton jButtonIndicadores;
    private javax.swing.JButton jButtonIngredientes;
    private javax.swing.JButton jButtonMedidas;
    private javax.swing.JButton jButtonPedidos;
    private javax.swing.JButton jButtonReceitas;
    private javax.swing.JButton jButtonTarefas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
