/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.awt.event.FocusListener;
import java.awt.event.KeyListener;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;
import javax.swing.JSpinner;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.TableModel;

/**
 *
 * @author andguerra
 */
public class ViewIngrediente extends javax.swing.JFrame {

    /**
     * Creates new form ViewIngrediente
     */
    public ViewIngrediente() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        ImageIcon check = new ImageIcon("Images/success-menor.png");
        jButtonSalvarMedida.setIcon(check);
        ImageIcon proximo = new ImageIcon("Images/next-azul-menor.png");
        jButtonProximaMedida.setIcon(proximo);
        ImageIcon anterior = new ImageIcon("Images/previous-azul-menor.png");
        jButtonMedidaAnterior.setIcon(anterior);
        ImageIcon novoEndereco = new ImageIcon("Images/plus-menor.png");
        jButtonNovaMedida.setIcon(novoEndereco);
        
        ImageIcon editar = new ImageIcon("Images/edit.png");
        jButtonEditarMedida.setIcon(editar);
        jButtonEditarIngrediente.setIcon(editar);
        
        ImageIcon excluir = new ImageIcon("Images/delete.png");
        jButtonExcluirMedida.setIcon(excluir);
        jButtonExcluirIngrediente.setIcon(excluir);
        
        visibleEditarIngrediente(false);
        visibleExcluirIngredienteTelaCadastro(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldBuscaIngrediente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableIngredientes = new javax.swing.JTable();
        jButtonVisualizarIngrediente = new javax.swing.JButton();
        jButtonExcluirIngredienteTelaBusca = new javax.swing.JButton();
        jButtonVoltarAoMenuTelaBusca = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldIdIngrediente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNomeIngrediente = new javax.swing.JTextField();
        jButtonSalvarMedida = new javax.swing.JButton();
        jButtonNovaMedida = new javax.swing.JButton();
        jButtonEditarMedida = new javax.swing.JButton();
        jButtonExcluirMedida = new javax.swing.JButton();
        jButtonMedidaAnterior = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabelPaginaMedida = new javax.swing.JLabel();
        jButtonProximaMedida = new javax.swing.JButton();
        jButtonSalvarTelaCadastro = new javax.swing.JButton();
        jButtonLimparTelaCadastro = new javax.swing.JButton();
        jButtonVoltarTelaCadastro = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNomeMedida = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jSpinnerQuantidadeConversao = new javax.swing.JSpinner();
        jComboBoxConversao = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jButtonEditarIngrediente = new javax.swing.JButton();
        jButtonExcluirIngrediente = new javax.swing.JButton();
        jComboBoxUnidadePadrao = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabelMedida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DoceIra - Ingredientes e Medidas");

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(965, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextFieldBuscaIngrediente.setText("Digite sua pesquisa aqui...");
        jTextFieldBuscaIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscaIngredienteActionPerformed(evt);
            }
        });

        jTableIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, ""},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Medida", "Quantidade em estoque"
            }
        ));
        jScrollPane1.setViewportView(jTableIngredientes);

        jButtonVisualizarIngrediente.setText("Visualizar");
        jButtonVisualizarIngrediente.setEnabled(false);

        jButtonExcluirIngredienteTelaBusca.setText("Excluir");
        jButtonExcluirIngredienteTelaBusca.setEnabled(false);

        jButtonVoltarAoMenuTelaBusca.setText("Voltar ao Menu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButtonVisualizarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)
                        .addComponent(jButtonExcluirIngredienteTelaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonVoltarAoMenuTelaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
                    .addComponent(jTextFieldBuscaIngrediente))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jTextFieldBuscaIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVisualizarIngrediente)
                    .addComponent(jButtonExcluirIngredienteTelaBusca)
                    .addComponent(jButtonVoltarAoMenuTelaBusca))
                .addGap(30, 30, 30))
        );

        jTabbedPane1.addTab("Busca", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(815, 500));

        jLabel11.setText("ID");

        jTextFieldIdIngrediente.setEnabled(false);

        jLabel2.setText("Nome");

        jButtonNovaMedida.setEnabled(false);

        jButtonEditarMedida.setEnabled(false);

        jButtonExcluirMedida.setEnabled(false);

        jButtonMedidaAnterior.setEnabled(false);

        jLabel10.setText("Página");

        jLabelPaginaMedida.setText("1");

        jButtonProximaMedida.setEnabled(false);

        jButtonSalvarTelaCadastro.setText("Salvar");

        jButtonLimparTelaCadastro.setText("Limpar");

        jButtonVoltarTelaCadastro.setText("Voltar ao Menu");

        jLabel3.setText("Medidas e conversões");

        jLabel4.setText("Medida");

        jLabel20.setText("Quantidade");

        jSpinnerQuantidadeConversao.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, 9.9999997952E10d, 0.1d));

        jComboBoxConversao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gramas", "Mililitros", "Unidades" }));

        jComboBoxUnidadePadrao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gramas", "Mililitros", "Unidades" }));

        jLabel5.setText("Unidade de medida padrão");

        jLabelMedida.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldIdIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(jTextFieldNomeIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEditarIngrediente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluirIngrediente))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jComboBoxUnidadePadrao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(65, 65, 65))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jButtonSalvarTelaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149)
                        .addComponent(jButtonLimparTelaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129)
                        .addComponent(jButtonVoltarTelaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonSalvarMedida)
                                .addGap(31, 31, 31)
                                .addComponent(jButtonNovaMedida)
                                .addGap(33, 33, 33)
                                .addComponent(jButtonEditarMedida)
                                .addGap(34, 34, 34)
                                .addComponent(jButtonExcluirMedida)
                                .addGap(320, 320, 320)
                                .addComponent(jButtonMedidaAnterior)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel10)
                                .addGap(6, 6, 6)
                                .addComponent(jLabelPaginaMedida)
                                .addGap(10, 10, 10)
                                .addComponent(jButtonProximaMedida))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelMedida)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jTextFieldNomeMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jSpinnerQuantidadeConversao, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(jComboBoxConversao, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldIdIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNomeIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jComboBoxUnidadePadrao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel11)))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonExcluirIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonEditarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNomeMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSpinnerQuantidadeConversao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20))
                    .addComponent(jComboBoxConversao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4)))
                .addGap(32, 32, 32)
                .addComponent(jLabelMedida)
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSalvarMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNovaMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditarMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluirMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMedidaAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabelPaginaMedida)
                    .addComponent(jButtonProximaMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSalvarTelaCadastro)
                    .addComponent(jButtonLimparTelaCadastro)
                    .addComponent(jButtonVoltarTelaCadastro))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cadastro", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBuscaIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscaIngredienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscaIngredienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewIngrediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewIngrediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewIngrediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewIngrediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewIngrediente().setVisible(true);
            }
        });
    }
    
    public String getIdIngrediente() {
        return jTextFieldIdIngrediente.getText();
    }

    public void setIdIngrediente(int idIngrediente) {
        jTextFieldIdIngrediente.setText(String.valueOf(idIngrediente));
    }
    
    public String getNomeIngrediente() {
        return jTextFieldNomeIngrediente.getText();
    }

    public void setNomeIngrediente(String nomeIngrediente) {
        jTextFieldNomeIngrediente.setText(nomeIngrediente);
    }
    
    public String getUnidadePadrao() {
        return jComboBoxUnidadePadrao.getSelectedItem().toString();
    }

    public void setUnidadePadrao(String unidadePadrao) {
        jComboBoxUnidadePadrao.setSelectedItem(unidadePadrao);
    }
    
    public String getNomeMedida() {
        return jTextFieldNomeMedida.getText();
    }

    public void setNomeMedida(String nomeMedida) {
        jTextFieldNomeMedida.setText(nomeMedida);
    }
    
    public String getPesquisa() {
        return jTextFieldBuscaIngrediente.getText();
    }

    public void setPesquisa(String pesquisa) {
        jTextFieldBuscaIngrediente.setText(pesquisa);
    }
    
    public String getCodigoMedida() {
        return jLabelMedida.getText();
    }
    
    public void setPaginaMedida(int idMedida) {
        jLabelPaginaMedida.setText(String.valueOf(idMedida));
    }
    
    public String getPaginaMedida() {
        return jLabelPaginaMedida.getText();
    }

    public void setCodigoMedida(int codigo) {
        jLabelMedida.setText(String.valueOf(codigo));
    }
    
    public String getQuantidadeConversao() {
        return String.valueOf(jSpinnerQuantidadeConversao.getValue());
    }

    public void setQuantidadeConversao(Double quantidadeDeConversao) {
        jSpinnerQuantidadeConversao.setValue(quantidadeDeConversao);
    }
    
    public String getUnidadeConversao() {
        return jComboBoxConversao.getSelectedItem().toString();
    }

    public void setUnidadeConversao(String unidadeConversao) {
        jComboBoxConversao.setSelectedItem(unidadeConversao);
    }
    
    public void jTextFieldPesquisaFocusListener(FocusListener listenerForjTextFieldPesquisa) {
        jTextFieldBuscaIngrediente.addFocusListener(listenerForjTextFieldPesquisa);
    }
    
    public void jTextFieldPesquisaKeyListener(KeyListener listenerForjTextFieldPesquisa) {
        jTextFieldBuscaIngrediente.addKeyListener(listenerForjTextFieldPesquisa);
    }
        
    public void salvarIngredienteTelaCadastroListener(ActionListener listenerForjButtonSalvarIngrediente) {
        jButtonSalvarTelaCadastro.addActionListener(listenerForjButtonSalvarIngrediente);
    }
    
    public void visualizarIngredienteListener(ActionListener listenerForjButtonVisualizarIngrediente) {
        jButtonVisualizarIngrediente.addActionListener(listenerForjButtonVisualizarIngrediente);
    }
    
    public void novaMedidaListener(ActionListener listenerForjButtonNovaMedida) {
        jButtonNovaMedida.addActionListener(listenerForjButtonNovaMedida);
    }
    
    public void voltarTelaCadastroListener(ActionListener listenerForjButtonVoltarTelaCadastroListener) {
        jButtonVoltarTelaCadastro.addActionListener(listenerForjButtonVoltarTelaCadastroListener);
    }
    
    public void voltarTelaBuscaListener(ActionListener listenerForjButtonVoltarTelaBusca) {
        jButtonVoltarAoMenuTelaBusca.addActionListener(listenerForjButtonVoltarTelaBusca);
    }
    
    public void excluirIngredienteTelaBuscaListener(ActionListener listenerForjButtonExcluirIngredienteTelaBusca) {
        jButtonExcluirIngredienteTelaBusca.addActionListener(listenerForjButtonExcluirIngredienteTelaBusca);
    }
    
    public void excluirMedidaListener(ActionListener listenerForjButtonExcluirMedida) {
        jButtonExcluirMedida.addActionListener(listenerForjButtonExcluirMedida);
    }
    
    public void proximaMedidaListener(ActionListener listenerForjButtonProximaMedida) {
        jButtonProximaMedida.addActionListener(listenerForjButtonProximaMedida);
    }
    
    public void medidaAnteriorListener(ActionListener listenerForjButtonMedidaAnterior) {
        jButtonMedidaAnterior.addActionListener(listenerForjButtonMedidaAnterior);
    }
    
    public void editarMedidaListener(ActionListener listenerForjButtonEditarMedida) {
        jButtonEditarMedida.addActionListener(listenerForjButtonEditarMedida);
    }
    
    public void editarIngredienteListener(ActionListener listenerForjButtonEditarIngrediente) {
        jButtonEditarIngrediente.addActionListener(listenerForjButtonEditarIngrediente);
    }
    
    public void salvarMedidaListener(ActionListener listenerForjButtonSalvarMedida) {
        jButtonSalvarMedida.addActionListener(listenerForjButtonSalvarMedida);
    }
    
    public void tabelaIngredientesMouseListener(MouseListener listenerForTabelaClientes) {
        jTableIngredientes.addMouseListener(listenerForTabelaClientes);
    }
    
    public String getIDSelecaoTabelaIngrediente(){
        return String.valueOf(jTableIngredientes.getValueAt(jTableIngredientes.getSelectedRow(), 0));
    }
    
    public void setTableModel (TableModel tableModel){
        jTableIngredientes.setModel(tableModel);
    }
    
    public void painelTelaIngrediente(int index){
        jTabbedPane1.setSelectedIndex(index);
    }
    
    public void visibleEditarIngrediente(boolean x) {
        jButtonEditarIngrediente.setVisible(x);
    }
    
    public void visibleExcluirIngredienteTelaCadastro(boolean x) {
        jButtonExcluirIngrediente.setVisible(x);
    }
    
    public void enabledSalvarTelaCadastro(boolean x) {
        jButtonSalvarTelaCadastro.setEnabled(x);
    }
    
    public void enabledLimparCamposIngrediente(boolean x) {
        jButtonLimparTelaCadastro.setEnabled(x);
    }

    public void enabledVoltar(boolean x) {
        jButtonVoltarTelaCadastro.setEnabled(x);
    }
    
    public void enabledSalvarMedida(boolean x) {
        jButtonSalvarMedida.setEnabled(x);
    }

    public void enabledNovaMedida(boolean x) {
        jButtonNovaMedida.setEnabled(x);
    }

    public void enabledEditar(boolean x) {
        jButtonEditarMedida.setEnabled(x);
    }

    public void enabledExcluirMedida(boolean x) {
        jButtonExcluirMedida.setEnabled(x);
    }
    
    public void enabledExcluirIngredienteTelaBusca(boolean x) {
        jButtonExcluirIngredienteTelaBusca.setEnabled(x);
    }
    

    public void enabledProximaMedida(boolean x) {
        jButtonProximaMedida.setEnabled(x);
    }

    public void enabledMedidaAnterior(boolean x) {
        jButtonMedidaAnterior.setEnabled(x);
    }

    public void enabledVisualizarIngrediente(boolean x) {
        jButtonVisualizarIngrediente.setEnabled(x);
    }

    public void enabledVoltarDaBusca(boolean x) {
        jButtonVoltarAoMenuTelaBusca.setEnabled(x);
    }
    
    public void enabledQuantidadeConversao(boolean x) {
        jSpinnerQuantidadeConversao.setEnabled(x);
    }
    
    public void enabledNomeMedida(boolean x) {
        jTextFieldNomeMedida.setEnabled(x);
    }
    
    public void enabledNomeIngrediente(boolean x) {
        jTextFieldNomeIngrediente.setEnabled(x);
    }
    
    public void enabledUnidadePadrao(boolean x) {
        jComboBoxUnidadePadrao.setEnabled(x);
    }
    
    public void enabledUnidadeConversao(boolean x) {
        jComboBoxConversao.setEnabled(x);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditarIngrediente;
    private javax.swing.JButton jButtonEditarMedida;
    private javax.swing.JButton jButtonExcluirIngrediente;
    private javax.swing.JButton jButtonExcluirIngredienteTelaBusca;
    private javax.swing.JButton jButtonExcluirMedida;
    private javax.swing.JButton jButtonLimparTelaCadastro;
    private javax.swing.JButton jButtonMedidaAnterior;
    private javax.swing.JButton jButtonNovaMedida;
    private javax.swing.JButton jButtonProximaMedida;
    private javax.swing.JButton jButtonSalvarMedida;
    private javax.swing.JButton jButtonSalvarTelaCadastro;
    private javax.swing.JButton jButtonVisualizarIngrediente;
    private javax.swing.JButton jButtonVoltarAoMenuTelaBusca;
    private javax.swing.JButton jButtonVoltarTelaCadastro;
    private javax.swing.JComboBox<String> jComboBoxConversao;
    private javax.swing.JComboBox<String> jComboBoxUnidadePadrao;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelMedida;
    private javax.swing.JLabel jLabelPaginaMedida;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSpinner jSpinnerQuantidadeConversao;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableIngredientes;
    private javax.swing.JTextField jTextFieldBuscaIngrediente;
    private javax.swing.JTextField jTextFieldIdIngrediente;
    private javax.swing.JTextField jTextFieldNomeIngrediente;
    private javax.swing.JTextField jTextFieldNomeMedida;
    // End of variables declaration//GEN-END:variables
}
